from __future__ import annotations

from .models import EventImpact, FactorScore, KnowledgeEdge, KnowledgeNode, MorningBriefItem, PredictionRecord

FACTOR_SCORES = [
    FactorScore(
        name="Brent 原油",
        symbol="BRENT",
        direction="利多",
        change="+2.8%",
        strength="强",
        contribution=18,
        route="原油 -> 石脑油 -> PX -> PTA",
        reason="中东风险升温叠加 OPEC+ 减产预期，原油风险溢价上升。",
    ),
    FactorScore(
        name="PX 亚洲",
        symbol="PX",
        direction="利多",
        change="+1.6%",
        strength="中强",
        contribution=14,
        route="PX -> PTA",
        reason="石脑油成本支撑增强，亚洲 PX 供应弹性偏低。",
    ),
    FactorScore(
        name="PTA",
        symbol="TA",
        direction="利多",
        change="+1.1%",
        strength="强",
        contribution=12,
        route="PTA -> 聚酯原料成本",
        reason="PX 上涨和装置检修共同强化成本支撑。",
    ),
    FactorScore(
        name="MEG",
        symbol="EG",
        direction="利空",
        change="-0.4%",
        strength="中",
        contribution=-8,
        route="MEG -> 聚酯原料成本",
        reason="港口库存偏高，煤制供应恢复，对整体成本压力形成抵消。",
    ),
    FactorScore(
        name="动力煤",
        symbol="COAL",
        direction="中性",
        change="+0.2%",
        strength="弱",
        contribution=1,
        route="煤炭 -> 煤制 MEG",
        reason="港口价格窄幅波动，煤制 MEG 成本端暂未出现强驱动。",
    ),
    FactorScore(
        name="人民币汇率",
        symbol="USDCNY",
        direction="利多",
        change="小幅贬值",
        strength="弱",
        contribution=3,
        route="汇率 -> 进口成本",
        reason="人民币小幅走弱提高进口原料人民币成本。",
    ),
    FactorScore(
        name="美元指数",
        symbol="DXY",
        direction="利空",
        change="+0.5%",
        strength="弱",
        contribution=-2,
        route="美元 -> 大宗商品",
        reason="美元走强压制部分商品风险偏好。",
    ),
]


EVENTS = [
    EventImpact(
        event_id="evt_opec_cut_signal",
        title="OPEC+ 释放延长减产信号",
        event_type="energy_policy",
        nature="供应端利多",
        horizon="3-14 天",
        evidence_level="B",
        confidence=0.78,
        affected_products=["crude_oil", "naphtha", "PX", "PTA"],
        impact_chain=[
            "OPEC+ 减产预期",
            "原油供应预期收紧",
            "石脑油成本上升",
            "PX/PTA 成本支撑",
            "上游原料成本压力增强",
        ],
        judgement="短期利多原油和 PX，对 PTA 成本支撑明显；若需求走弱或库存增加，利多持续性会下降。",
        stakeholders=["OPEC+ 产油国", "美国页岩油企业", "原油进口国", "能源交易资金", "下游化工企业"],
        beneficiaries=["产油国", "能源企业", "原油多头资金"],
        harmed=["原油进口国", "聚酯产业链", "下游化工企业"],
        counter_evidence=["EIA 库存超预期增加", "全球需求走弱", "市场已提前交易减产预期"],
    ),
    EventImpact(
        event_id="evt_redsea_shipping_risk",
        title="红海航运风险重新升温",
        event_type="shipping_geopolitics",
        nature="运费与风险溢价利多",
        horizon="1-4 周",
        evidence_level="C",
        confidence=0.64,
        affected_products=["crude_oil", "naphtha", "PX", "MEG", "freight"],
        impact_chain=[
            "航线安全风险上升",
            "绕航和保险成本增加",
            "油轮/集运运费上涨",
            "进口原料到港不确定性增强",
            "成本压力上行",
        ],
        judgement="该事件更偏运输与风险溢价，不等同于实际供应中断，需要用油轮、港口和运价数据验证。",
        stakeholders=["航运公司", "保险机构", "中东产油国", "进口商", "能源资金"],
        beneficiaries=["部分航运公司", "油轮运价多头", "能源风险资产"],
        harmed=["进口商", "下游化工企业", "依赖红海航线的贸易商"],
        counter_evidence=["袭击未扩大", "护航提升通行率", "运价指数没有同步上行"],
    ),
    EventImpact(
        event_id="evt_meg_inventory_high",
        title="华东 MEG 港口库存高位震荡",
        event_type="industry_inventory",
        nature="成本压力抵消",
        horizon="7-21 天",
        evidence_level="B",
        confidence=0.72,
        affected_products=["MEG", "polyester_feedstock_cost"],
        impact_chain=["MEG 到港稳定", "港口库存高位", "现货上行动能不足", "聚酯成本压力被部分抵消"],
        judgement="MEG 仍是本周上游成本压力的主要抵消项，除非出现连续去库或装置意外停车。",
        stakeholders=["MEG 港口贸易商", "煤制 MEG 工厂", "聚酯工厂", "期货资金"],
        beneficiaries=["下游采购方", "库存较低的聚酯工厂"],
        harmed=["MEG 多头资金", "高成本 MEG 工厂"],
        counter_evidence=["煤制装置降负", "进口船期延后", "下游聚酯开工超预期回升"],
    ),
]


PREDICTIONS = [
    PredictionRecord(
        prediction_id="pred_20260522_0830_7d",
        created_at="2026-05-22T08:30:00+08:00",
        target="POY/DTY_upstream_cost_pressure",
        horizon="7d",
        direction="震荡偏强",
        index_range=(68, 76),
        confidence=0.76,
        factor_snapshot=FACTOR_SCORES,
        review_status="pending",
    ),
    PredictionRecord(
        prediction_id="pred_20260515_0830_7d",
        created_at="2026-05-15T08:30:00+08:00",
        target="POY/DTY_upstream_cost_pressure",
        horizon="7d",
        direction="偏强",
        index_range=(66, 74),
        confidence=0.69,
        factor_snapshot=FACTOR_SCORES,
        review_status="reviewed",
    ),
    PredictionRecord(
        prediction_id="pred_20260508_0830_7d",
        created_at="2026-05-08T08:30:00+08:00",
        target="POY/DTY_upstream_cost_pressure",
        horizon="7d",
        direction="震荡",
        index_range=(58, 66),
        confidence=0.61,
        factor_snapshot=FACTOR_SCORES,
        review_status="reviewed",
    ),
]


MORNING_BRIEF = [
    MorningBriefItem(
        title="原油风险溢价",
        body="Brent 走强，市场重新计入中东冲突和 OPEC+ 供应管理风险。短期对石脑油、PX 和 PTA 偏利多。",
        priority="high",
        linked_factors=["BRENT", "PX", "TA"],
    ),
    MorningBriefItem(
        title="PTA 链条主导",
        body="PX 上涨和 PTA 装置检修共同强化成本支撑；若加工费继续压缩，现货跟涨弹性需要重点观察。",
        priority="high",
        linked_factors=["PX", "TA"],
    ),
    MorningBriefItem(
        title="MEG 抵消项",
        body="MEG 港口库存偏高，煤制供应恢复削弱上行弹性，对整体聚酯原料成本压力形成抵消。",
        priority="medium",
        linked_factors=["EG", "COAL"],
    ),
]


KNOWLEDGE_NODES = [
    KnowledgeNode(
        node_id="crude_oil",
        label="原油",
        node_type="commodity",
        summary="POY/DTY 上游成本的最外层驱动，主要通过石脑油、PX、PTA 传导。",
        evidence_level="A",
        aliases=["Brent", "WTI", "SC 原油"],
    ),
    KnowledgeNode(
        node_id="naphtha",
        label="石脑油",
        node_type="commodity",
        summary="PX 的关键成本输入，跟随原油但会受炼厂开工和裂解需求影响。",
        evidence_level="B",
        aliases=["轻质石脑油"],
    ),
    KnowledgeNode(
        node_id="px",
        label="PX",
        node_type="commodity",
        summary="PTA 的直接原料，PXN 价差用于区分成本推动和自身供需推动。",
        evidence_level="B",
        aliases=["对二甲苯"],
    ),
    KnowledgeNode(
        node_id="pta",
        label="PTA",
        node_type="commodity",
        summary="聚酯链条核心原料之一，是 POY/DTY 上游成本压力的主导节点。",
        evidence_level="A",
        aliases=["精对苯二甲酸", "TA"],
    ),
    KnowledgeNode(
        node_id="meg",
        label="MEG",
        node_type="commodity",
        summary="聚酯链条核心原料之一，油制和煤制路径并存，库存对价格弹性影响大。",
        evidence_level="A",
        aliases=["乙二醇", "EG"],
    ),
    KnowledgeNode(
        node_id="opec",
        label="OPEC+",
        node_type="organization",
        summary="通过产量政策影响原油供需预期和风险溢价。",
        evidence_level="A",
        aliases=["OPEC", "OPEC+"],
    ),
    KnowledgeNode(
        node_id="cost_pressure_index",
        label="上游原料成本压力指数",
        node_type="output",
        summary="将原油、PX、PTA、MEG、煤炭、汇率、航运和事件因子合成为 0-100 指数。",
        evidence_level="B",
        aliases=["成本压力指数"],
    ),
]


KNOWLEDGE_EDGES = [
    KnowledgeEdge(source_id="crude_oil", target_id="naphtha", relation="成本传导", polarity="up", confidence=0.86),
    KnowledgeEdge(source_id="naphtha", target_id="px", relation="成本传导", polarity="up", confidence=0.82),
    KnowledgeEdge(source_id="px", target_id="pta", relation="直接原料", polarity="up", confidence=0.91),
    KnowledgeEdge(
        source_id="pta",
        target_id="cost_pressure_index",
        relation="聚酯原料成本",
        polarity="up",
        confidence=0.92,
    ),
    KnowledgeEdge(
        source_id="meg",
        target_id="cost_pressure_index",
        relation="聚酯原料成本",
        polarity="up",
        confidence=0.84,
    ),
    KnowledgeEdge(source_id="opec", target_id="crude_oil", relation="供应政策", polarity="up", confidence=0.78),
]
